// ==UserScript==
// @name          ROBUX New Logo Replacement
// @namespace     http://userstyles.org
// @description	  A style that replaces the new ROBUX icon with the old one.
// @author        gustavo242
// @homepage      https://userstyles.org/styles/204058
// @include       https://www.roblox.com*
// @include       https://web.roblox.com*
// @include       http://roblox.com/*
// @include       https://roblox.com/*
// @include       http://*.roblox.com/*
// @include       https://*.roblox.com/*
// @run-at        document-start
// @version       0.20220422193739
// ==/UserScript==
(function() {var css = "";
if (false || (document.location.href.indexOf("https://www.roblox.com") == 0) || (document.location.href.indexOf("https://web.roblox.com") == 0))
	css += [
		".light-theme .icon-default-economy-28x28,",
		".light-theme .icon-robux-28x28,",
		".light-theme .icon-robux-gold-28x28,",
		".light-theme .icon-robux-white,",
		".dark-theme .icon-default-economy-28x28,",
		".dark-theme .icon-robux-28x28,",
		".dark-theme .icon-robux-gold-28x28,",
		".dark-theme .icon-robux-white {",
		"	background-image: url(https://images.rbxcdn.com/3a9b44283e65ae1ead90defcb0bdcb6e-economy_28x28_dark.svg);",
		"}",
		".light-theme .icon-default-branded-16x16,",
		".light-theme .icon-robux-16x16,",
		".light-theme .icon-robux-gray-16x16,",
		".light-theme .icon-robux-white-16x16 {",
		"	background-image: url(https://images.rbxcdn.com/757f696cbfd2d8fcde61d219cead6a2c-branded_04182018.svg);",
		"}",
		".light-theme .icon-robux-28x28,",
		".robux-upsell .unsubscribed .icon-robux-white,",
		".dark-theme .icon-robux-28x28,",
		".robux-upsell .unsubscribed .icon-robux-white {",
		"	background-image: url(https://images.rbxcdn.com/757f696cbfd2d8fcde61d219cead6a2c-branded_04182018.svg);",
		"	background-position: 0;",
		"	background-size: 58px;",
		"}",
		".icon-robux-16x16,",
		".light-theme .icon-robux-16x16,",
		".robux-downsell .icon-robux-gray,",
		".dark-theme .icon-robux-16x16,",
		".light-theme .icon-robux-gray-16x16,",
		".btn-economy-robux-white-lg span[class^=\"icon-\"] {",
		"	background-image: url(https://images.rbxcdn.com/757f696cbfd2d8fcde61d219cead6a2c-branded_04182018.svg);",
		"	background-position: 0;",
		"}",
		".light-theme .icon-robux-16x16 {",
		"	background-position: 0 -76px;",
		"	background-size: 38px auto;",
		"}",
		".light-theme .icon-robux-gray-16x16 {",
		"	background-position: 0 -114px;",
		"	background-size: 38px auto;",
		"}",
		".dark-theme .robux-downsell .icon-robux-gray {",
		"	background-position: 0 -168px;",
		"}",
		".icon-robux-16x16 {",
		"	background-position: 0 -76px;",
		"	background-size: 38px;",
		"}",
		".light-theme .icon-robux-28x28 {",
		"	background-position: 0 -117px;",
		"}",
		"#nav-robux-icon .icon-robux-28x28 {",
		"	background-position: 0 -196px;",
		"}",
		"#nav-robux-icon .icon-robux-28x28:hover {",
		"	background-position: -28px -196px;",
		"}",
		".nav-robux-icon {",
		"	cursor: pointer;",
		"}",
		".icon-robux-price-container .icon-robux-28x28 {",
		"	background-image: url(https://svgur.com/i/GP3.svg);",
		"	background-size: 28px;",
		"}",
		".robux-upsell .unsubscribed .icon-robux-white {",
		"	background-position: 0 -203px;",
		"}",
		".robux-downsell .icon-robux-gray {",
		"	background-position: 0 -112px;",
		"}",
		".btn-economy-robux-white-lg span[class^=\"icon-\"] {",
		"	background-position: 0 -252px;",
		"}",
		".light-theme .icon-robux-gray-16x16 {",
		"	background-position: 0 -73px !important;",
		"	background-size: 24px auto !important;",
		"	height: 12px;",
		"	width: 12px;",
		"}",
		".gotham-font.light-theme .dark-theme .refresh-link-icon:after,",
		".gotham-font.light-theme .dark-theme .see-all-link-icon:after,",
		".light-theme .game-card-info .dark-theme .info-label.icon-playing-counts-gray,",
		".light-theme .game-card-info .dark-theme .info-label.icon-playing-counts-gray-white-70,",
		".light-theme .game-card-info .dark-theme .info-label.icon-votes-gray,",
		".light-theme .game-card-info .dark-theme .info-label.icon-votes-gray-white-70,",
		".light-theme .gotham-font .dark-theme .refresh-link-icon:after,",
		".light-theme .gotham-font .dark-theme .see-all-link-icon:after {",
		"	background-image: url(https://static.rbxcdn.com/images/Shared/games_08302018.svg);",
		"}",
		".light-theme .typing {",
		"	background-image: url(\"https://images.rbxcdn.com/04e6dac32004283d9d4827e38f25c993-typing.gif\")",
		"}",
		".icon-premium-120x120 {",
		"	background-image: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODgiIGhlaWdodD0iODgiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTgwIDBhOCA4IDAgMCAxIDggOHY3MmE4IDggMCAwIDEtNy43NSA3Ljk5Nkw4MCA4OEg0MnYtOGgzOFY4SDh2ODBhOCA4IDAgMCAxLTgtOFY4QTggOCAwIDAgMSA3Ljc1LjAwNEw4IDBoNzJ6bS02IDE0djYwaC04VjIySDIydjY2aC04VjE0aDYwek00MiA2MHYtOGgxMFYzNkgzNnY1MmgtOFYyOGgzMnYzMkg0MnptMjQgNnY4SDQydi04aDI0eiIgZmlsbD0iI0ZGRiIgZmlsbC1ydWxlPSJldmVub2RkIi8+PC9zdmc+);",
		"	background-size: 120px;",
		"}",
		".icon-robux-medium,",
		".icon-robux-medium-desktop {",
		"	background-image: url(https://images.rbxcdn.com/757f696cbfd2d8fcde61d219cead6a2c-branded_04182018.svg);",
		"	background-size: calc(100% + 160px);",
		"	background-position: 0 -1100px;",
		"	filter: sepia(100%) saturate(600%) brightness(80%) hue-rotate(330deg);",
		"	opacity: 0.9;",
		"	position: relative;",
		"	z-index: -1;",
		"}",
		".premium-landing-page .stipend-section .robux-bg {",
		"	background-image: url(https://images.rbxcdn.com/757f696cbfd2d8fcde61d219cead6a2c-branded_04182018.svg);",
		"	background-size: calc(100% + 1000px);",
		"	filter: sepia(100%) saturate(600%) brightness(80%) hue-rotate(330deg);",
		"	opacity: 0.2;",
		"	background-position: 0 -5600px;",
		"}",
		".icon-robux-130x130::after {",
		"	content: \'no see\';",
		"	font-size: 0;",
		"	display: inline-block;",
		"	width: 130px;",
		"	height: 130px;",
		"	position: relative;",
		"	top: -85px;",
		"	z-index: -1;",
		"	background-image: url(https://images.rbxcdn.com/757f696cbfd2d8fcde61d219cead6a2c-branded_04182018.svg);",
		"	background-size: calc(100% + 130px);",
		"	background-position: 0 -910px;",
		"	filter: sepia(100%) saturate(600%) brightness(80%) hue-rotate(330deg);",
		"	visibility: initial;",
		"}",
		".icon-robux-130x130 {",
		"	visibility: hidden;",
		"}",
		".premium-landing-page .trade-benefit-section .icon-ten-percent-more {",
		"	visibility: initial;",
		"}",
		".icon-trade-160x160 {",
		"	background-image: url(https://images.rbxcdn.com/f4000b6d03a0df7153556d2514045629-navigation_10022018.svg);",
		"	background-size: calc(100% + 160px);",
		"	background-position: 0 -1760px;",
		"	filter: sepia(100%) saturate(800%) brightness(600%) hue-rotate(160deg);",
		"}",
		".benefits-detail-container {",
		"	background-color: white;",
		"}",
		".light-theme .icon-premium-88x88 {",
		"	background-image: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODgiIGhlaWdodD0iODgiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTgwIDBhOCA4IDAgMCAxIDggOHY3MmE4IDggMCAwIDEtNy43NSA3Ljk5Nkw4MCA4OEg0MnYtOGgzOFY4SDh2ODBhOCA4IDAgMCAxLTgtOFY4QTggOCAwIDAgMSA3Ljc1LjAwNEw4IDBoNzJ6bS02IDE0djYwaC04VjIySDIydjY2aC04VjE0aDYwek00MiA2MHYtOGgxMFYzNkgzNnY1MmgtOFYyOGgzMnYzMkg0MnptMjQgNnY4SDQydi04aDI0eiIgZmlsbD0iI0ZGRiIgZmlsbC1ydWxlPSJldmVub2RkIi8+PC9zdmc+);",
		"	filter: brightness(20%);",
		"",
		"}",
		".dark-theme .left-col-list li a > span,",
		".dark-theme .left-col-list li > div > span {",
		"	color: #ccc;",
		"}",
		".dark-theme .left-col-list li a:hover > span,",
		".dark-theme .left-col-list li > div:hover > span {",
		"	color: #fff;",
		"}",
		".dark-theme .left-col-list li a:hover div span[class^=\"icon\"] {",
		"	filter: saturate(0) brightness(1000%);",
		"}",
		".dark-theme .left-col-list li div:hover div span[class^=\"icon\"] {",
		"	filter: saturate(0) brightness(1000%);",
		"}",
		".light-theme .left-col-list li div:hover div span.icon-nav-shop {",
		"	background-position: -28px -420px;",
		"}",
		".dark-theme .div-table-cell > .icon-robux-28x28 {",
		"	background-position: 0 -204px;",
		"}",
		".dark-theme .icon-robux-16x16 {",
		"	background-position: 0 -132px;",
		"}",
		"",
		".dark-theme .icon-default-economy-small,",
		".dark-theme .icon-robux-16x16,",
		".dark-theme .icon-robux-gold-16x16,",
		".dark-theme .icon-robux-gray-16x16,",
		".dark-theme .icon-robux-white-16x16 {",
		"	background-image: url(https://images.rbxcdn.com/757f696cbfd2d8fcde61d219cead6a2c-branded_04182018.svg)",
		"}",
		".dark-theme .icon-robux-gray-16x16 {",
		"	background-position: 0 -121px;",
		"	background-size: 40px;",
		"}"
	].join("\n");
if (false || (document.domain == "roblox.com" || document.domain.substring(document.domain.indexOf(".roblox.com") + 1) == "roblox.com"))
	css += [
		".light-theme .rbx-header {",
		"    background-color: #d1d3d5;",
		"	border: none;",
		"}",
		".light-theme .rbx-header .text-header, .light-theme .rbx-header .text-header:active, .light-theme .rbx-header .text-header:focus, .light-theme .rbx-header .text-header:hover, .light-theme .rbx-header .text-header:link, .light-theme .rbx-header .text-header:visited {",
		"    color: #ffffff;",
		"}",
		".light-theme .icon-default-navigation, .light-theme .icon-nav-menu, .light-theme .icon-nav-notification-stream, .light-theme .icon-nav-robux, .light-theme .icon-nav-search, .light-theme .icon-nav-search-white, .light-theme .icon-nav-settings {",
		"    background-image: url(https://images.rbxcdn.com/f4000b6d03a0df7153556d2514045629-navigation_10022018.svg);",
		"}"
	].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();
